apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJkbUZ6ZW05c09tZG9jRjlaY25wWlJreEpTSEJDVWtka1kyVjZXWGRxUzFkS1FreHBjRFZhVkhnd1FrZzFhRUU9IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
