apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    # Указываем, что будем использовать Nginx Ingress Controller
#    kubernetes.io/ingress.class: "nginx"   # устаревшее
    # новое
    ingressClassName: nginx
    # Отключаем редирект с HTTP на HTTPS (для простоты локального тестирования)
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: cinemaabyss.example.com
      http:
        paths:
          # 1. КОРНЕВОЙ ПУТЬ (должен идти на API Gateway/Proxy Service)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-service # Service Name: proxy-service (работает на порту 8000)
                port:
                  number: 8000

          # 2. EVENTS SERVICE
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: events-service
                port:
                  number: 8082

          # 3. MONOLITH SERVICE (Users, Payments, Subscriptions)
          # Используем service: monolith, который работает на порту 8080
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: monolith
                port:
                  number: 8080

          - path: /api/subscriptions
            pathType: Prefix
            backend:
              service:
                name: monolith
                port:
                  number: 8080

          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: monolith
                port:
                  number: 8080